[package]
name = "roc"
version = "0.1.0"
authors = ["IDAM <innes.andersonmorrison@gmail.com>"]
edition = "2018"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
select = "0.4.3"

[dev-dependencies]
test-case = "1.0"
