[package]
name = "roc"
version = "0.1.1"
authors = [
    "sminez <innes.andersonmorrison@gmail.com>",
    "mchlrhw <4028654+mchlrhw@users.noreply.github.com>"
]
edition = "2018"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
select = "0.4.3"

[dev-dependencies]
test-case = "1.0"
